version: '3.7'

services:

   
  application:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    tty: true
    networks:
      - backend
      
  
networks:
  backend: